# Generated by Django 6.0.5 on 2026-05-20 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('ssh_user', models.CharField(help_text='Remote SSH user (e.g. ubuntu, root)', max_length=255)),
                ('token', models.CharField(help_text='Unique bearer token for sync auth', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='organizations.organization')),
            ],
            options={
                'db_table': 'servers',
            },
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_title', models.CharField(max_length=255)),
                ('key_payload', models.TextField(help_text='SSH public key material (openssh format)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_keys', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_keys', to=settings.AUTH_USER_MODEL)),
                ('servers', models.ManyToManyField(blank=True, related_name='assigned_keys', to='core.server')),
            ],
            options={
                'db_table': 'public_keys',
            },
        ),
    ]
