# Generated by Django 6.0.5 on 2026-05-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='deploy_to_all',
            field=models.BooleanField(default=True, help_text='If True, key deploys to all active org servers. If False, only to selected servers.'),
        ),
    ]
