# Generated by Django 6.0.6 on 2026-06-14 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_server_allow_self_service'),
        ('organizations', '0004_auth_user_email_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_kind', models.CharField(choices=[('user', 'User'), ('server', 'Server'), ('system', 'System')], default='user', max_length=16)),
                ('action', models.CharField(help_text="Dot-namespaced verb, e.g. 'publickey.created', 'server.token_rotated'", max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=32)),
                ('target_id', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='May be null for org-less events (e.g. login attempt for unknown user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_logs_organiz_86ff70_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_logs_target__9fc8de_idx')],
            },
        ),
    ]
