# Generated by Django 6.0.6 on 2026-06-14 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
        ('organizations', '0004_auth_user_email_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publickey',
            constraint=models.UniqueConstraint(fields=('organization', 'key_payload'), name='uniq_pubkey_payload_per_org'),
        ),
    ]
