# Generated by Django 6.0.6 on 2026-06-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_server_last_synced_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publickey',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['created_at']},
        ),
    ]
