# Generated by Django 6.0.5 on 2026-05-21 20:43

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for this key (e.g. ci-server-prod)', max_length=255)),
                ('key_prefix', models.CharField(editable=False, max_length=32)),
                ('key_hash', models.CharField(editable=False, help_text='SHA-256 of the full token', max_length=64)),
                ('scopes', models.JSONField(default=list, help_text='List of TokenScope values')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization')),
            ],
            options={
                'db_table': 'api_keys',
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['key_prefix'], name='api_keys_key_pre_971d85_btree')],
            },
        ),
    ]
