# Generated by Django 6.0.6 on 2026-06-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auth_user_email_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['created_at']},
        ),
    ]
