# Generated by Django 6.0.6 on 2026-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizationinvite_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invite_email_theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=8),
        ),
    ]
